name: lyricfierfna
base: core18
version: '0.4'
summary: Lyrics search for Spotify app
description: |
  Lyricfiers lyrics for Spotify. Modified by fnaufel to work with
  ncspot.
grade: stable
confinement: classic
environment:
  TMPDIR: $XDG_RUNTIME_DIR

parts:
  lyricfierfna:
    plugin: go
    go-importpath: github.com/fnaufel/lyricfier2
    source: .
    source-type: local
    build-packages:
      - gcc
      - git
      - libgtk-3-dev
      - libappindicator3-dev
      - libwebkit2gtk-4.0-dev
    stage-packages:
      - libappindicator3-1
      - libdbusmenu-glib4
      - libdbusmenu-gtk3-4
      - libindicator3-7

apps:
  lyricfierfna:
    extensions: [gnome-3-28]
    command: bin/lyricfierfna
    plugs:
      - mpris
      - network
      - network-bind
      - unity7
      - desktop
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      RUNNING_IN_SNAP: 1

